export type Vec3 = { x: number; y: number; z: number };
export type Segment = { from: Vec3; to: Vec3; motion: "rapid" | "linear"; feed: number; feedSet: boolean; line: number; arc?: boolean };
export type Diagnostic = { code: string; severity: "info" | "warning" | "error"; message: string; line?: number };
export type FixtureBox = { name: string; min: Vec3; max: Vec3 };
export type Workcell = { machine: string; limits: { min: Vec3; max: Vec3 }; rapidFeed: number; feedLimit?: number; fixtures: FixtureBox[] };
export type MachineState = { control: string; offsets: Record<string, Vec3>; tools: Record<string, { diameter?: number; length?: number }> };
export type ProgramAssumptions = { units: "mm" | "in"; offsetsUsed: string[]; toolsUsed: string[]; envelope: { min: Vec3; max: Vec3 } | null };
export type ParseResult = { segments: Segment[]; diagnostics: Diagnostic[]; units: "mm" | "in"; assumptions: ProgramAssumptions };
export type AnalysisResult = { diagnostics: Diagnostic[]; verdict: "pass" | "caution" | "block"; stats: { segments: number; distanceMm: number; rapidDistanceMm: number; durationSec: number } };